# Generated by Django 4.1.10 on 2023-08-23 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import petfriend_api.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('genre', models.SmallIntegerField(choices=[(1, 'boy'), (2, 'girl')])),
                ('species', models.SmallIntegerField(choices=[(1, 'dog'), (2, 'cat'), (3, 'rabbit'), (4, 'guinea pig'), (5, 'hamster'), (6, 'ferret'), (7, 'birds'), (8, 'horse'), (9, 'birds'), (10, 'pig'), (11, 'cow'), (0, 'others')])),
                ('variety', models.CharField(max_length=128, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('profile_image', models.ImageField(null=True, upload_to=petfriend_api.models.pet_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recovered', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfriend_api.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetFriendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfriend_api.petfrienduser'),
        ),
    ]
