# Generated by Django 4.1.10 on 2023-08-23 16:57

from django.db import migrations, models
import petfriend_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=petfriend_api.models.pet_directory_path),
        ),
    ]
