# Generated by Django 4.1.10 on 2023-08-24 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriend_api', '0002_alter_pet_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
