# Generated by Django 4.1.10 on 2023-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriend_api', '0003_alter_pet_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
