version: "3.9"

services:
  web:
    container_name: rest_api
    build: .
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
      - web
volumes:
  postgres_data:
  rabbitmq_data: